---
abstract: 'The great new WebService::Smartling!'
author:
  - 'Matthew Cox, C<< <mcox at cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Smartling
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  JSON: 0
  Params::Validate: 0
  Readonly: 0
  WebService::Simple: 0
  perl: 5.6.0
  version: 0
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 0.000004
